# Generated by Django 5.2 on 2025-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_filtrogenerico'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMonitoreada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_anterior', models.TextField(blank=True, null=True)),
                ('html_actual', models.TextField(blank=True, null=True)),
                ('hash_md5', models.CharField(blank=True, max_length=64)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('has_changed', models.BooleanField(default=False)),
                ('contador_palabras', models.IntegerField(default=0)),
            ],
        ),
    ]
