# Generated by Django 5.2 on 2025-05-28 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_urlmonitoreada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLMonitoreada',
        ),
        migrations.AddField(
            model_name='urlmonitor',
            name='contador_palabras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlmonitor',
            name='hash_md5',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='urlmonitor',
            name='html_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlmonitor',
            name='html_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlmonitor',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 5, 28, 8, 26, 25, 814888, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
