# Generated by Django 5.2 on 2025-04-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
    ]
